version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vaquita_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: vaquita_db
    ports:
      - "5432:5432"
    volumes:
      - vaquita_data:/var/lib/postgresql/data

volumes:
  vaquita_data: